import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "@/libs/appcontext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>{children}</Provider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
