export const education = [
  {
    label: "Post Graduation",
    value: "PG",
    courses: [
      { label: "Master of Science (M.Sc)", value: "MSC" },
      { label: "Master of Arts (M.A)", value: "MA" },
      { label: "Master of Business Administration (MBA)", value: "MBA" },
      { label: "Master of Technology (M.Tech)", value: "MTECH" },
      { label: "Master of Computer Applications (MCA)", value: "MCA" },
      { label: "Master of Fine Arts (MFA)", value: "MFA" },
      { label: "Master of Social Work (MSW)", value: "MSW" },
      { label: "Master of Education (M.Ed)", value: "MED" },
      { label: "Master of Laws (LLM)", value: "LLM" },
    ],
  },
  {
    label: "Graduation",
    value: "UG",
    courses: [
      { label: "Bachelor of Science (B.Sc)", value: "BSC" },
      { label: "Bachelor of Arts (B.A)", value: "BA" },
      { label: "Bachelor of Commerce (B.Com)", value: "BCOM" },
      { label: "Bachelor of Technology (B.Tech)", value: "BTECH" },
      { label: "Bachelor of Computer Applications (BCA)", value: "BCA" },
      { label: "Bachelor of Fine Arts (BFA)", value: "BFA" },
      { label: "Bachelor of Social Work (BSW)", value: "BSW" },
      { label: "Bachelor of Education (B.Ed)", value: "BED" },
      { label: "Bachelor of Laws (LLB)", value: "LLB" },
      { label: "Bachelor of Business Administration (BBA)", value: "BBA" },
    ],
  },
  {
    label: "Diploma",
    value: "DIP",
    courses: [
      { label: "Diploma in Engineering", value: "DENG" },
      { label: "Diploma in Management", value: "DM" },
      { label: "Diploma in Computer Applications", value: "DCA" },
      { label: "Diploma in Education", value: "DED" },
      { label: "Diploma in Medical Laboratory Technology", value: "DMLT" },
      { label: "Diploma in Pharmacy", value: "DPH" },
      { label: "Diploma in Nursing", value: "DN" },
      { label: "Diploma in Fine Arts", value: "DFA" },
    ],
  },
];

export const universities = [
  { label: "Indian Institute of Technology Bombay", value: "IITB" },
  { label: "Indian Institute of Technology Delhi", value: "IITD" },
  { label: "Indian Institute of Technology Kanpur", value: "IITK" },
  { label: "Indian Institute of Technology Madras", value: "IITM" },
  { label: "Indian Institute of Technology Kharagpur", value: "IITKH" },
  { label: "Indian Institute of Science Bangalore", value: "IISc" },
  { label: "Jawaharlal Nehru University", value: "JNU" },
  { label: "University of Delhi", value: "DU" },
  { label: "Banaras Hindu University", value: "BHU" },
  { label: "University of Hyderabad", value: "UOH" },
  { label: "Jadavpur University", value: "JU" },
  { label: "University of Calcutta", value: "CU" },
  { label: "Amrita Vishwa Vidyapeetham", value: "AMRITA" },
  { label: "Jamia Millia Islamia", value: "JMI" },
  { label: "Savitribai Phule Pune University", value: "SPPU" },
  { label: "Manipal Academy of Higher Education", value: "MAHE" },
  { label: "Birla Institute of Technology and Science, Pilani", value: "BITS" },
  { label: "Vellore Institute of Technology", value: "VIT" },
  { label: "Aligarh Muslim University", value: "AMU" },
  { label: "University of Mumbai", value: "MU" },
  { label: "Anna University", value: "AU" },
  { label: "Osmania University", value: "OU" },
  { label: "Guru Gobind Singh Indraprastha University", value: "GGSIPU" },
  { label: "Visvesvaraya Technological University", value: "VTU" },
  { label: "SRM Institute of Science and Technology", value: "SRM" },
];
